### PR TITLE
Have schema comments handle table names that aren't just symbols.

### PR DESCRIPTION
**Pull request by chanks**
I have a model with an unpleasantly-rendered table name, like so:

```ruby
class Item < Sequel::Model(Sequel.qualify(:public, :items))
end

# Table: #<Sequel::SQL::QualifiedIdentifier:0x0000564506c88588>
# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Columns:
# ...
```

This change fixes the table name in the annotation to be `public.items`.

Not immediately sure why the spec I added changes the id column default to be `PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY` whereas the similar spec uses `PRIMARY KEY DEFAULT nextval('categories_id_seq'::regclass)`...

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch, this is definitely what we want to do.  For the spec, can you make the default similar to the other defaults so the specs will work on older versions of PostgreSQL (I'm guessing the default is something like `nextval('public.items_id_seq'::regclass)`)?  The specs automatically convert the older style to the newer style if PostgreSQL 10.2+ is used.

**Comment by chanks** [comment]
Ah! I see. Alright, should be fixed.

**Comment by jeremyevans** [comment]
Spec fix looks good, will merge shortly.

**Comment by chanks** [comment]
Thank you!

**Pull request merged**
