### PR TITLE
output table comments on postgresql databases

### PR DESCRIPTION
**Pull request by TSMMark**
@jeremyevans This was very straightforward to implement, thanks for the direction.

FWIW, I also tested installing the gem via this branch's commit ref in Gemfile, and it works as intended in my project.

---

> From sequel-talk google group
> Re: Add SQL comments in migrations
>
> You are correct that table comments are not currently expected to be picked up.  I'm open to a PR that adds support for them.  I didn't author the column comment support, so I don't really remember what is involved.  I assume a query per table to get the table comment, and if a table comment exists, displaying it the annotation, maybe after the table name and before the column information.
>
> Thanks,
> Jeremy

### CODE REVIEW

**Comment by TSMMark** [comment]
I noticed there's no CI but I think this should not break anything else. Unfortunately my `rake` locally has some issues getting the PK comment format exactly as the specs want it. I'm guessing a PG version difference.

```
  1) Failure:
Sequel::Annotate#test_0004_#schema_info should return the model schema comment [spec/sequel-annotate_spec.rb:303]:
--- expected
+++ actual
@@ -1,7 +1,7 @@
 "# Table: comment_tests
 #  comment_tests table comment
 # Columns:
-#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY |
-#  name | text    |                                              | name column comment
+#  id   | integer | PRIMARY KEY DEFAULT nextval('comment_tests_id_seq'::regclass) |
+#  name | text    |                                                               | name column comment
 # Indexes:
 #  comment_tests_pkey | PRIMARY KEY btree (id)"
```

However the relevant part including the table's comment passes the expectation of the spec.

**Comment by jeremyevans** [comment]
Thanks for working on this.  From a brief review, this looks good.  I'll do a full review and merge tomorrow.  I'll also see if I can setup CI for this project.

**Comment by TSMMark** [comment]
Hi @jeremyevan, is there anything blocking a new gem release that you need help with?

**Comment by jeremyevans** [comment]
@TSMMark Nope.

**Comment by TSMMark** [comment]
Hey @jeremyevans how's it going? Any plans to release this in a new gem version?

**Comment by jeremyevans** [comment]
Considering it's been a while since this has been merged and no other changes have been requested, I can work on a release today.  Thanks for the reminder.

**Pull request merged**
